#!/bin/bash
set -e

cd /ruby-bench-suite/liquid
# branch is temporary
git pull --rebase origin liquid-test

cd /liquid
git pull --rebase origin master

# move some liquid/performance files to bench-suite
mv /liquid/performance/tests      /ruby-bench-suite/liquid/benchmarks/support
rm /liquid/performance/shopify/liquid.rb
mv /liquid/performance/shopify/* /ruby-bench-suite/liquid/benchmarks/support/shopify
mv /liquid/performance/theme_runner.rb /ruby-bench-suite/liquid/benchmarks/support

if [ "$INCLUDE_PATTERNS" ]; then
  PATTERNS="--pattern $INCLUDE_PATTERNS"
fi

# Install gem dependencies to run the benchmarks
gem install benchmark-ips
gem install liquid

# --local is temporary
ruby /ruby-bench-suite/liquid/benchmarks/driver.rb $PATTERNS
